In [53]:
# NumPyをインポートするコードを記述する
import numpy as np
# AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# 行列の積の計算をするコードを記述する
result = np.dot(A, B)
# Step3の計算結果を表示するコードを記述する
print(result)
# 行列の要素の最大値を求めるコードを記述する
result.max()


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47